### ISSUE TITLE
Using partition_key on a non-existing topic causes Rdkafka::RdkafkaError (leader_not_available)

### ISSUE THREAD

**Issue by mensfeld** [karafka/rdkafka-ruby#163]
When using the `partition_key` with a non-existing topic, the topic is supposed to be created upon `partition_count` execution when `auto.create.topics.enable` is set to `true`.

ref: https://github.com/appsignal/rdkafka-ruby/blob/380678f6a7ba8f7791aa190288caaae1a7b5fab2/lib/rdkafka/producer.rb#L101

This indeed is the case, however, there is one problem with the current implementation and there are no tests covering it:

There is a slight (few ms) delay in between the topic creation and its availability. What that means, is we end up not having this partition or topic upon moving forward in the code yet (we have stale metadata). 

To illustrate that, you can just try to publish messages to non-existing topics generated in a sequence. It will end up with:

```ruby
     # ./spec/lib/water_drop/producer_spec.rb:298:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Rdkafka::RdkafkaError:
     #   Broker: Leader not available (leader_not_available)
     #   ./spec/lib/water_drop/producer_spec.rb:63:in `new'
```
The solution here would be to wait for a fixed time, so Kafka can initialize the topic and librdkafka can refresh the metadata:

```ruby
    def produce(topic:, payload: nil, key: nil, partition: nil, partition_key: nil, timestamp: nil, headers: nil)
     # pre if code...

      if partition_key
        begin
          partition_count = partition_count(topic)
        rescue Rdkafka::RdkafkaError
          sleep(0.01)
        end

        # If the topic is not present, set to -1
        partition = Rdkafka::Bindings.partitioner(partition_key, partition_count) if partition_count
      end

     # rest of the code
```

We need to give librdkafka enough time to refresh the metadata internally as said here:

https://docs.confluent.io/platform/current/clients/librdkafka/html/md_INTRODUCTION.html

```
Error: Temporary errors due to stale metadata

Broker errors ERR_LEADER_NOT_AVAILABLE, ERR_NOT_LEADER_FOR_PARTITION.

These errors are considered temporary and a retry is warranted, a metadata request is automatically sent to find a new leader for the partition.

A retry by librdkafka at this point will not cause duplicate messages.
```

(on the CI I also see `invalid_replication_factor` and `transport` except two mentioned above)

As I said, current specs do not cover this case, since the topic for specs is auto created upon kafka initialization (`partitioner_test_topic`).

My suggestion would be:

1. catch those cases based on the error message (like i did)
2. retry with backoff
3. if all is good move on
4. if error is persistent raise as the cause may be different and we do not want an infinite loop

The backoff would be good as we need to compensate for the network in between the producer and the cluster.

**Comment by mensfeld** [comment]
Closing. This is expected. That is, librdkafka docs state that you are not supposed to use non-synchronized topic.
