### ISSUE TITLE
Error while installing  rdkafka (0.1.11)

### ISSUE THREAD

**Issue by arishsymplr** [karafka/rdkafka-ruby#488]
`Downloading v0.11.0.tar.gz
Extracting v0.11.0.tar.gz into tmp/arm64-apple-darwin23.5.0/ports/librdkafka/0.11.0... OK
Running 'configure' for librdkafka 0.11.0... OK
Running 'compile' for librdkafka 0.11.0... ERROR. Please review logs to see what happened:
----- contents of '/Users/evry/.rvm/gems/ruby-3.1.4/gems/rdkafka-0.1.11/ext/tmp/arm64-apple-darwin23.5.0/ports/librdkafka/0.11.0/compile.log' -----
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -c rdkafka.c -o rdkafka.o
rdkafka.c:299:2: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
        _ERR_DESC(RD_KAFKA_RESP_ERR__BEGIN, NULL),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -c snappy.c -o snappy.o
snappy.c:1410:9: warning: variable 'written' set but not used [-Wunused-but-set-variable]
        size_t written = 0;
               ^
1 warning generated.
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -c rdgz.c -o rdgz.o
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -c rdkafka_lz4.c -o rdkafka_lz4.o
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -O3 -c xxhash.c -o xxhash.o
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -c rddl.c -o rddl.o
gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/opt/homebrew/Cellar/openssl@3/3.3.0/include
-I/opt/homebrew/Cellar/lz4/1.9.4/include -I/opt/homebrew/Cellar/openssl@3/3.3.0/include -c rdkafka_plugin.c -o rdkafka_plugin.o
Generating linker script librdkafka.lds from rdkafka.h
env: python: No such file or directory
make[1]: *** [librdkafka.lds] Error 127
make: *** [libs] Error 2
----- end of file -----
rake aborted!
Failed to complete compile task
/Users/evry/.rvm/gems/ruby-3.1.4/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:504:in `block in execute'
/Users/evry/.rvm/gems/ruby-3.1.4/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:470:in `chdir'
/Users/evry/.rvm/gems/ruby-3.1.4/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:470:in `execute'
/Users/evry/.rvm/gems/ruby-3.1.4/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:172:in `compile'
/Users/evry/.rvm/gems/ruby-3.1.4/gems/mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:215:in `cook'
/Users/evry/.rvm/gems/ruby-3.1.4/gems/rdkafka-0.1.11/ext/Rakefile:10:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/evry/.rvm/gems/ruby-3.1.4/gems/rdkafka-0.1.11 for inspection.
Results logged to /Users/evry/.rvm/gems/ruby-3.1.4/extensions/arm64-darwin-22/3.1.0/rdkafka-0.1.11/gem_make.out

  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'
  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/ext/rake_builder.rb:28:in `build'
  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:171:in `build_extension'
  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in build_extensions'
  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `build_extensions'
  /Users/evry/.rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/rubygems/installer.rb:843:in `build_extensions'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/source/rubygems.rb:202:in `install'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/worker.rb:62:in `apply_func'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `loop'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/worker.rb:54:in `process_queue'
  /Users/evry/.rvm/gems/ruby-3.1.4/gems/bundler-2.4.17/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing rdkafka (0.1.11), and Bundler cannot continue.

In Gemfile:
  rdkafka`
  
  For time being I am going with 0.17.0 which is installed without any issues.

**Comment by mensfeld** [comment]
[0.1.11](https://rubygems.org/gems/rdkafka/versions/0.1.11) - September 10, 2017 (13 KB)

now supported. Won't do anything about it. Please use newer versions that work.

**Comment by arishsymplr** [comment]
@mensfeld  the above issue with 0.1.11 not with 0.17.0

**Comment by arishsymplr** [comment]
@mensfeld  the above issue with 0.1.11 not with 0.17.0

**Comment by mensfeld** [comment]
>  the above issue with 0.1.11 not with 0.17.0

0.1.11 is OLD and NOT supported.

If you do not have issue with 0.17.0 then use it because it is newer.

**Comment by arishsymplr** [comment]
Thanks 👍
